### ISSUE TITLE
does not work on windows 11

### ISSUE THREAD

**Issue by Kr1sp11** [ModernFlyouts-Community/ModernFlyouts#1360]
### ModernFlyouts Version

0.9.3.0

### Windows version

windows 11 pro 24H2

### OS build

26100.1742

### Platform

x64

### Area(s) with issue?

General, Audio Flyout, Media Flyout, Lock keys Flyout, Battery Flyout, Audio Tray Flyout, Camera Flyout, Mic Flyout, Welcome / ModernFlyouts OOBE

### Steps to reproduce

the program is running, it is displayed in the tray, but when changing the sound or pressing caps lock, etc. the window is not displayed

### ✔️ Expected Behavior

window display

### ❌ Actual Behavior

window not displayed

### Other Software

music, google crhrome etc.

**Comment by neradp** [comment]
#1349

**Comment by MaD-Myke** [comment]
I have the same issue. Program runs, I have granted it admin privileges and removed/reinstalled to no avail. I am going to try a previous version and will update this post of that resolves the issue.

**Comment by HadpCap** [comment]
I have the same problem

**Comment by neradp** [comment]
Why guys, do you not reading previous issues ?

Version [v.0.10.0-beta4 ](https://github.com/ModernFlyouts-Community/ModernFlyouts/releases/tag/v0.10.0-beta.4)  works quite well on Win 11 24H2.

You have to download and install it manually in powershell because the certificate provided has expired.

`Add-AppPackage ".\ModernFlyouts.Package_0.9.8513.0_x86_x64_arm64.msixbundle" -AllowUnsigned`

**Comment by HadpCap** [comment]
How can I do it is that I don't know much?

**Comment by Samuel12321** [comment]
use https://github.com/ModernFlyouts-Community/ModernFlyouts/releases/tag/v0.10.0-beta.5
