### ISSUE TITLE
Merge language zh-CN and zh-Hans

### ISSUE THREAD

**Issue by FrzMtrsprt** [ModernFlyouts-Community/ModernFlyouts#250]
As **zh-Hans** (Simplified Chinese) and **zh-CN** (Chinese used in Mainland China) is basically the same varient of Chinese language, there's no need to keep both, or it may cause confusion to Chinese users. 
They should be merged into one single language translation file. I suggest that **zh-Hans** should be deleted and **zh-CN** should be kept untouched.

**Comment by ShankarBUS** [comment]
https://github.com/ShankarBUS/ModernFlyouts/pull/219#issuecomment-727267554

This is the reason.

Hey @Samuel12321,

How about also switching zh-Hant to zh-TW?

@imgradeone @FrzMtrsprt

Would that reduce confusing?

**Comment by FrzMtrsprt** [comment]
Well, **zh-Hant** has two main sebsets: **zh-HK** and **zh-TW**, and they are kind of different in word usage, so...would be better if we add another **zh-HK** translation.

**Comment by ShankarBUS** [comment]
So zh-TW and zh-HK instead of zh-Hant (traditional) and zk-CN instead of zh-Hans (simplified)?

Is that ok?

**Comment by FrzMtrsprt** [comment]
Yes, I think this would be the best solution.

**Comment by ShankarBUS** [comment]
Hey @FrzMtrsprt,

Does the system default option actually pick up your system language?

We got some complaints that it didn't work for Chinese.
Does it work now?

**Comment by FrzMtrsprt** [comment]
Yes, it's working perfectly, except for the menu item "Personalization" is not being translated.

**Comment by Samuel12321** [comment]
> It's working perfectly, except for the menu item "Personalization" is not being translated...Will that be fixed in the next release?

which version are you using, that bug was fixed a while ago.

**Comment by FrzMtrsprt** [comment]
> > It's working perfectly, except for the menu item "Personalization" is not being translated...Will that be fixed in the next release?
> 
> which version are you using, that bug was fixed a while ago.

I installed it from Microsoft Store. In System Settings it says 0.8.1.0, but in the app it says 0.8.0.1, could it be a wrong package was uploaded?

**Comment by Samuel12321** [comment]
> I installed it from Microsoft Store. In System Settings it says 0.8.1.0, but in the app it says 0.8.0.1, could it be a wrong package was uploaded?

no, that was just a mistake on my part. When we released 0.8.1 i changed the package version number but forgot to change the version number displayed in the app.😁

> which version are you using, that bug was fixed a while ago.

On second thoughts, that may have been part of the 0.8.2 release. Please wait for that to be available.

**Comment by Samuel12321** [comment]
My only concern is that everyone else seems to be moving away from ZH-CN, ZH-TW .... to just zh-HANS and ZH-HANT to simplify things. Are we managing locale correctly? 
Any thoughts @ShankarBUS?

**Comment by ShankarBUS** [comment]
Or else we could do some workarounds within the code.

We could remap zh-CN (system) to zh-Hans (app) and zh-TW (system) to zh-Hant (app) when applying the language.

**Comment by TragicLifeHu** [comment]
There's three zh-Hans (Simplified) in the world: zh-CN (China Mainland), zh-SG (Singapore) and zh-MY (Malaysia)
There's also three zh-Hant (Traditional) in the world: zh-TW (Taiwan), zh-MO (Macau) and zh-HK (Hong Kong).
For zh-Hant, zh-TW has more influence, but actually they have the difference (just a bit, from the font to the phrase)

By default the Chinese system recognizes the region (CN, TW), not the variant (Hant, Hans). What's more is that usually Malaysia, Singapore and Macau users won't contribute for their own language.

The further decision is up to developers then.

**Comment by imgradeone** [comment]
in my opinion, merging zh-CN and zh-Hans is okay, and it will be better for Chinese Simplified users, because at present, selecting between zh-CN or zh-Hans DO makes confusions. (even though they are exactly the same)

But, for zh-Hant, it is different. so we have to make some change for zh-Hant to match the usage(?) in both Hong Kong and Taiwan.

remapping the language files is also a great idea. (especially for zh-MO, zh-SG and zh-MY)

---

鉴于 issue 主是中国用户 ~~还是个 homo~~ ，顺便再写个中文版的回复吧。

我觉得合并 zh-Hans 和 zh-CN 其实是个好主意，毕竟当前版本的软件，选择语言的列表有两个代表简体中文的语言包，会让人犯选择困难症。（虽然这俩都一样）

至于 zh-Hant 就需要针对香港和台湾地区的用语习惯做出一些微调。

当然重定向（？）语言文件也是个好主意，尤其对于 zh-MO、zh-SG、zh-MY 来说。

**Comment by ShankarBUS** [comment]
So, what's the conclusion people?

Should we
- just keep zh-HANS and zh-HANT
- keep zh-CN, zh-TW and add zh-HK, zh-MO, zh-SG and zh-MY
- do both (i.e. zh-HANS, zh-HANT, zh-CN, zh-TW, zh-HK, zh-MO, zh-SG and zh-MY)

What should we do?

**Comment by TragicLifeHu** [comment]
I think use zh-CN + zh-TW is the best solution

as zh-CN/zh-TW can't not represent for the zh-Hans/zh-Hant, and our translation is optimized for zh-CN/zh-TW, not the whole Chinese

**Comment by ShankarBUS** [comment]
So only zh-CN and zh-TW and no other regional Chinese langs?

@Samuel12321, what do you say?

**Comment by Samuel12321** [comment]
My vote would be on remapping everything to just zh-Hans and zh-Hant.
In the language list just list "Chinese simplified" and "Chinese Traditional".
This would simplify things a lot and reduce complexity and maintenance, they are the recommended 'modern' way of doing this and they are considered "region neutral".
Otherwise we are going to end up with tones of different translations.
**@ShankarBUS its your call**, but everyone else is migrating away from zh-cn and zh-tw.

**Comment by ShankarBUS** [comment]
@Samuel12321,

I agree.
We can do the remapping within the code like I said before.

> **its your call**

Nah mate. I know nothing about localisation.
You're the boss here. It's **your call**. I can do just the remapping.

**Comment by yume-chan** [comment]
FYI.

`zh` is the language code for `Chinese`

`Hans` and `Hant` refer to writing system `Han` (`s` for `Simplified` and `t` for `Traditional`). While `cmn` refers to the spoken language [Mandarin](https://iso639-3.sil.org/code/cmn). (I can say "we write `Hans` or `Hant`, and speak in `cmn`")

`CN`, `HK`, `TW`, `SG` and others are region codes because different regions use slightly different words (same as `color` vs `colour` in `en-US` vs `en-UK`)

So if you are writing Chinese Simplified and using mainland Chinese wording, the full language code is `zh-Hans-CN`, if you also add voice, then it becomes `zh-cmn-Hans-CN`

Sorry for the complexity, but usually `zh-Hans` and `zh-Hant` are recommended and enough.

**Comment by ShankarBUS** [comment]
@yume-chan,

Thanks for confusing me further!

Very cool 👍

**Comment by imgradeone** [comment]
I think the best way is remapping, though.

**Comment by FrzMtrsprt** [comment]
Same, since we don't have a zh-HK translator for now.

**Comment by Samuel12321** [comment]
@ShankarBUS which release did you want this in?

**Comment by ShankarBUS** [comment]
Yes

**Comment by Samuel12321** [comment]
?

**Comment by ShankarBUS** [comment]
I just discovered another problem.

I had a look at one of Microsoft's project called WinUI. It has `zh-CN` and `zh-TW` for some reasons.

I guess we must stay inline with their approach. I mean they are huge company and don't use `zh-Hans` and `zh-Hant` means there must be some important reasons behind it.

I'm legit confused and blanked out. People here recommend to use `zh-Hans` and `zh-Hant`. MS there using `zh-CN` and `zh-TW`. I'm just a noob what am I supposed to do?

Most .NET based apps and libraries support `zh-Hans` and `zh-Hant`. So, `zh-Hans` and `zh-Hant` it is.

@Samuel12321, we could include this in the upcoming release.

**Comment by ShankarBUS** [comment]
I must thank you all for giving me ideas and suggestions regarding this problem.

Let's wait till https://github.com/Kinnara/ModernWpf/issues/202 is finalized.
We could revisit this issue once **Yimeng Wu** (@Kinnara) makes a solid decision.
They're the author of `ModernWpfUI` library and they're from China. They may have some knowledge on how to do this.

**Comment by Samuel12321** [comment]
Have changed it to just zh-CN and zh-TW to stay inline with winui.

Happy to change this again if anyone comes up with a better idea.
