### ISSUE TITLE
Feature Request: GitHub hosted Website

### ISSUE THREAD

**Issue by Samuel12321** [ModernFlyouts-Community/ModernFlyouts#262]
GitHub has a feature to create and host a free website for your app. Very quick and simple to use. See eartrumpets website https://eartrumpet.app/

**Comment by ShankarBUS** [comment]
Really? Wow! That's great. I forgot that GitHub pages exist 🤦‍♂️.

But unfortunately, I forgot HTML and CSS. It's has been 4 years since I last used them.

----

FAQ

> Do we need to buy a domain to host the website?

Not necessarily

> Is the website hosting free?

Obviously! (With some restrictions)

> Does GitHub allow custom domain names (say ModernFlyouts.app)?

Unfortunately no

GitHub only allows `username.github.io` as domain names for free.

We still need to buy a domain for using a custom domain name.

But that doesn't matter.
We can use GitHub's free service to host our website.

----

But I also don't to keep our usernames for a public opensource project.

One proper way would be to make an organisation account on GitHub (say ModernFlyouts), transfer this repo to the organisation and use the organisation's name to create a free domain (like modernflyouts.github.io).

What do you say?

**Comment by Samuel12321** [comment]
I think that's the best option, if you are happy with that.
As it is, i don't have access to GitHub pages for this repo.

> But unfortunately, I forgot HTML and CSS. It's has been 4 years since I last used them.

About the same for me too. If i recall correctly GitHub pages does offer a gui website creator.

**Comment by ShankarBUS** [comment]
Okay.

Can focus on GitHub pages post v1.0?

Currently the code commit frequency has been lowered dramatically (sorry for my inactivity 😅). If we keep up like this, we won't be able to release v1.0 within 3 months.

I wasted my free time playing with the logo and store images (still incomplete). (we'll also focus on this post v1.0)

Website is not our primary priority, right? I mean we still get users anyway.

Don't get wrong 😅.

**Comment by Samuel12321** [comment]
Agreed. Code is currently top priority.

**Comment by Samuel12321** [comment]
done, very basic website. Copied the styling from ear trumpet.
It's been a while since i have done html and css.
Everyone is free to improve it.

**Comment by Cyberdroid1** [comment]
Site is not properly displaying on mobile devices. The left side of banner is cut off.

**Comment by Cyberdroid1** [comment]
How do I contribute to it?

**Comment by Samuel12321** [comment]
https://github.com/ModernFlyouts-Community/ModernFlyouts/blob/main/docs/index.html

**Comment by Tropix126** [comment]
> Site is not properly displaying on mobile devices. The left side of banner is cut off.

I've made a PR to fix this.

**Comment by Tropix126** [comment]
If you guys need further help on anything HTML or CSS related, i'd be willing to help.

**Comment by ShankarBUS** [comment]
@Tropix126,

He he heyyyyyyyy!!!!!

Thank you so much bröthër!

**Comment by Samuel12321** [comment]
Hi @Tropix126 , thanks so much.
I'm quite rusty in HTML and css. If you have any suggestions or want to improve anything feel free to do so.
