### ISSUE TITLE
Bug: information mistake about "insert" and "overwrite" when switch between ssh and applications

### ISSUE THREAD

**Issue by lsylusiyao** [ModernFlyouts-Community/ModernFlyouts#299]
**Describe the bug:**
When I use `vim` in XShell-SSH and `Word` together, if I switch "insert" and "overwrite" modes in both the two software, it seems that the detection of the two modes would become a mess.

**To Reproduce:**

1. go to a vim editor in ssh
2. start an application (i.e. Word) in Windows
3. try switching to insert mode in vim, and now it shows "overwrite mode", which is wrong.
4. switch back to Word, press "Insert", now it should be "overwrite mode" but now it shows "insert mode".

**OS Version:**
 - Windows 10 Version: Windows 10 20H2

**ModernFlyouts Version:**
 - Version: 0.8.4.0

**Comment by Cyberdroid1** [comment]
Have a look at #90. Please see that issue.

@ShankarBUS Please close this issue.

**Comment by ShankarBUS** [comment]
No,

This issue is kind of unfixable.

Hear me out....

Each application have their own insert button key state.

That is, a program's insert mode will only be toggled if it's active.

So, let's say there are 3 windows (consider Text editors) and you press the insert key. Only the active app's insert mode will be toggled. Others apps would be unchanged.

But ModernFlyouts run all the time so it's value may be different from what program have cached.

One workaround would be to change the "Insert mode"/"Overtype mode" to "Insert Key".

**Comment by lsylusiyao** [comment]
@ShankarBUS Thanks for reply. 
When I created the issue I just considered that this may be a tough job. 
I have a suggestion to relieve the uncomfortable feeling about this. Since it couldn't be solved automatically, a button to change the state or set to default (insert mode) could be given on the window which will show out when switching the mode. For now the only way is to restart the software.

**Comment by ShankarBUS** [comment]
Show the flyout within the active window in which you toggled the insert key you say?

That'll be much harder that how it is now.

**Comment by lsylusiyao** [comment]
Yeah, I agree. Just showing "Insert Key" would be better.
