### ISSUE TITLE
Bug: ModernFlyouts gets hidden behind other topmost windows and not shown in Lockscreen

### ISSUE THREAD

**Issue by TharukaN97** [ModernFlyouts-Community/ModernFlyouts#32]
@TharukaN97,

When i use volume up/down , Brightness up/down when watching video in Fullscreen or While playing a game in Fullscreen, Modern Flyouts overlay not appearing top of full screen video / game.

@Sebastian1896,

When the Start Menu is present the flyout gets lost behind. The windows default one is always on top in any moment.

@validatedev,

I cannot see any popup for brightness, caps lock, etc. while the Windows lock screen is activated.

**Comment by ShankarBUS** [comment]
This is a known limitation. It will be fixed in version 1.0 release

**Comment by TharukaN97** [comment]
That's Awesome. Thanks 😊👍

**Comment by ShankarBUS** [comment]
I'm sorry you're experiencing this issue. This project originally (i.e. cloned from [AudioFlyout ](https://github.com/ADeltaX/AudioFlyout) by @ADeltaX) had the ability to show itself over every window but was removed temporarily due to some difficulties.

@ADeltaX, could you take care of this issue?

**Comment by ADeltaX** [comment]
Yes

**Comment by Cyberdroid1** [comment]
Any updates to this? Figured any workaround?

**Comment by ShankarBUS** [comment]
@Cyberdroid1,

Shhhh, KEEP QUIET!

Every one forgot this bug exists. Don't remind them!

**Comment by ShankarBUS** [comment]
I have stopped further progress on this because
- In order to make the flyout window top most, we have to use an undocumented API ([found out, elaborated and demonstrated](https://blog.adeltax.com/window-z-order-in-windows-10/) by @ADeltaX!) which only allows two modes (normal and ultimate [req. UI Access]) for normal apps. Other modes are prohibited to be only used by Microsoft signed applications.
- **.NET Core/.NET 5** doesn't support hosting **self-contained runtime** onto a **native process** (but it does that internally somehow). If anyone knows how to host a **self-contained .NET runtime** onto a **native (C++) process**, then please help me out.

Even though we can host a pre-installed **.NET runtime** (on the target machine) [i.e. we have to deploy our app as **framework-dependent** and force users to manually install **.NET 5 runtime** on their system] onto a native process, **self-contained .NET runtime** is impossible to be hosted in a native process AFAIK.

@ADeltaX, Could you tell me how to use the **`UI Access`** workaround for now?
How could we sign the application with a self signed certificate in order to use **UI Access**?

As you said the [installation guide of AudioFlyout](https://github.com/ADeltaX/AudioFlyout/blob/master/guide.md#what-are-the-differences)

> **AudioFlyoutUA.zip** --> doesn't make use of admin privilege but it makes use of **UI Access**. This will give access to create a **top top most** window, displayable even in lock screen.
> **Cons:** this requires to be extracted in a protected folder (ex: Program Files), and it should be signed.
> **Cons:** this is test signed, as a code signing certificate is expensive for me to obtain, which means you need to trust the certificate to run it.

@Samuel12321, told me that the application will automatically be signed with a proper certificate while passing through the **Store Certification** and that the signed certificate will be automatically be **installed** when the package is being installed.
Since we are using **MSIX** as the deployment method, we can be 100% sure that the package will be installed on `C:\Program Files\WindowsApps\`
We could use that until we figure out a better native hosting strategy.

**Comment by Samuel12321** [comment]
@ShankarBUS, could we we make the app framework dependant and bundle it with the framework using the .appinstaller dependancies?

**Comment by Cyberdroid1** [comment]
> @ShankarBUS, could we we make the app framework dependant and bundle it with the framework using the .appinstaller dependancies?

You can try this for the beta version. We can add a prompt to install .NET 5 from add a feature setting in control panel.

**Comment by ShankarBUS** [comment]
@Samuel12321,

That's the problem!
.NET 5 runtime is not published as a `Framework Package` and I read somewhere that they won't in the near future. So, it cant be added as dependency in the APPX package manifest or the appinstaller.

I also heard that MSIX doesn't provide custom actions (like pre-install functions to ensure dependencies).

So, that's that. Only self-contained 😢.

@Samuel12321, did I mention your statements correctly? Did I assume anything wrong?

**Comment by ShankarBUS** [comment]
@Cyberdroid1,

> You can try this for the beta version. We can add a prompt to install .NET 5 from add a feature setting in control panel.

I don't understand this properly. But let me assume that you meant to provide an option to download the .NET 5 runtime inside the settings window.

Our app wouldn't even start without the runtime!!! How could we show the settings if the wouldn't even start!!

If you meant something different, let me know.

**Comment by Samuel12321** [comment]
> @Samuel12321,
> 
> That's the problem!
> .NET 5 runtime is not published as a `Framework Package` and I read somewhere that they won't in the near future. So, it cant be added as dependency in the APPX package manifest or the appinstaller.

Of course, how silly of me to assume Microsoft would have done something logical.🤣

**Comment by Samuel12321** [comment]
What about [Desktop6](https://docs.microsoft.com/en-us/uwp/schemas/appxpackage/uapmanifestschema/element-desktop6-installactions)?

**Comment by Samuel12321** [comment]
or this? https://www.advancedinstaller.com/forums/viewtopic.php?f=7&t=41018#p110135

**Comment by jordanisaacs** [comment]
https://github.com/ModernFlyouts-Community/ModernFlyouts/issues/99#issuecomment-742037896

Would it be possible to implement this for the time being when full screen in a UWP app? Essentially automatically disable modernflyouts it when full screen and re-enable it when exit full screen. That way we are at least able to see volume changes even if is the ugly default UI.

**Comment by ShankarBUS** [comment]
WE ARE WORKING ON IT! This is our top priority for now. Most of the work has been done.

I even added the ability to detect full-screen apps. https://github.com/ModernFlyouts-Community/ModernFlyouts/blob/37bb061f8dfb486c4d8f76b1ec483e1e8d8e173d/ModernFlyouts.Core/Interop/NativeMethods.cs#L373

I will add the option to hide the flyout later in v0.10 or so.

**Comment by ShankarBUS** [comment]
Oh, I forgot to notify you all.

This bug is fixed and being worked on in the dev branch of this repository.

The flyout now even shows on top of the lock screen.

Smash the Like button, hit Share and Subscribe to my channel for more updates on this!!!
