### ISSUE TITLE
in V0.8.5 Displayed Windows Flyout for 1 time only on When First Time Use Sound Increase Or Decrease After Windows Startup

### ISSUE THREAD

**Issue by Mr-Snow-Skull** [ModernFlyouts-Community/ModernFlyouts#321]
**OS Version:**
 - Windows 10 Version: Windows 10 20H2

**ModernFlyouts Version:** 
 - Version: 0.8.5

**Additional context:**
Displayed Old Flyout on When First Time Use Sound Increase Or Decrease After Windows Startup

**Comment by ShankarBUS** [comment]
Hmm, that is I M P O S S I B L E due to these reasons:

- ɪᴍᴘᴏꜱꜱɪʙʟᴇ

- ǝlqıssodɯI

- ℑ𝔪𝔭𝔬𝔰𝔰𝔦𝔟𝔩𝔢

- 𝕴𝖒𝖕𝖔𝖘𝖘𝖎𝖇𝖑𝖊

- 𝕀𝕞𝕡𝕠𝕤𝕤𝕚𝕓𝕝𝕖

-Ｉｍｐｏｓｓｉｂｌｅ

- 🄸🄼🄿🄾🅂🅂🄸🄱🄻🄴

- ɘ|diꙅꙅoqmI

- I̷̛̭͌̒̐̌m̵̧̧̛͓͕͕͖̰̯̓̉͑p̷̛̳͚̝̠̽͋̂̑̐̀̉̕͜͠ö̵̜̗́̇̈́̿s̴̨̛̠̳͇̮̬̥͛̒͐̃̋͐̈̊̕s̸̡̡̧̱̱͖̬̜͑ͅī̷̳̗̃͝͝b̸͔̿͝ḻ̴̛͚̭̲̮̤̯̘͉̲̽̊̾̈́̂̄ȩ̶̡͉̲͉̳̿͒̐̍̈ͅ

- 🅸🅼🅿🅾🆂🆂🅸🅱🅻🅴

- ᵢₘₚₒₛₛᵢbₗₑ

- ᴵᵐᵖᵒˢˢⁱᵇˡᵉ

- Ⓘⓜⓟⓞⓢⓢⓘⓑⓛⓔ

- เ๓ק๏รรเ๒ɭє

- IɱρσʂʂιႦʅҽ

- ɨʍքօֆֆɨɮʟɛ

- ᎥᎷᎮᎧᏕᏕᎥᏰᏝᏋ

- ıɱ℘ơʂʂıცƖɛ

- i๓p໐ŞŞi๖lē

- 𝐈𝐦𝐩𝐨𝐬𝐬𝐢𝐛𝐥𝐞

- 𝘐𝘮𝘱𝘰𝘴𝘴𝘪𝘣𝘭𝘦

- 𝙄𝙢𝙥𝙤𝙨𝙨𝙞𝙗𝙡𝙚

- 𝙸𝚖𝚙𝚘𝚜𝚜𝚒𝚋𝚕𝚎

- IMPӨƧƧIBᄂΣ

- ιмρσѕѕιвℓє

- Ìmþð§§ïßlê

- ł₥₱Ø₴₴ł฿ⱠɆ

-丨爪卩ㄖ丂丂丨乃ㄥ乇

- ﾉﾶｱの丂丂ﾉ乃ﾚ乇

**Comment by Mr-Snow-Skull** [comment]
Sorry sir first time i cant describe my problem full

**Comment by Cyberdroid1** [comment]
Are you trying to instantly change volume after a boot? If so, can't help it.

**Comment by Mr-Snow-Skull** [comment]
Yes,

**Comment by ShankarBUS** [comment]
Unfortunately, this can't be fixed.

You have to live with this 😅.

**Comment by Mr-Snow-Skull** [comment]
Thanks for the details  👍
