### ISSUE TITLE
Feature Request: media background thumbnail modes [stretch, fit or fill] 

### ISSUE THREAD

**Issue by amrbashir** [ModernFlyouts-Community/ModernFlyouts#361]
**Is your feature request related to a problem? Please describe:**

The background thumbnail is not consistent, some thumbnails are big which covers the whole flyout but others don't which irritates me to be honest (symmertical ocd).

**Describe the solution you'd like:**

A new dropdown menu option where I can select one of three modes, stretch, fill, or fit.

Love your app though and appreciate your work.

**Comment by ShankarBUS** [comment]
*Whaaaaaaaaaaaat?*

I don't understand what you're trying to say properly.

Could you explain a bit clearly?

Are you talking about the thumbnail shown in the background?

Could you post some screenshots?

**Comment by amrbashir** [comment]
Yes, the thumbnail in the background. 

After some investigating, I found out that I was wrong, the thumbnails are consistent. I had a song playing with the same color as the flyout so I thought it was filling the whole flyout. So discard my comments about consistency, sorry for the inconvenience.

But still a different modes for this thumbnail would be kinda nice. 

Current mode is fine but I would like some other modes like stretching the image or fill the whole layout...etc. 
kinda like Windows 10 Background fit options.

![image](https://user-images.githubusercontent.com/48618675/104784662-6fa6aa00-5791-11eb-99ca-dfe9d6209f9f.png)

**Comment by ShankarBUS** [comment]
Ah Spotify!

This issue can't be fixed by providing an option to change the stretch mode.

This is a problem intentionally created by Spotify!
Look at this image, this is what they provide us as the thumbnail.

![](https://i.imgur.com/K92SE6p.png)

But you're in good hands! We fixed this issue by specifically cropping Spotify's thumbnails.

![](https://cdn.discordapp.com/attachments/788742640547004436/789461179759067156/unknown.png)

Hope that helps 🙂.

**Comment by amrbashir** [comment]
Yeah that's good enough for me. Again sorry for the inconvenience. keep up the good work.
