### ISSUE TITLE
Bug:

### ISSUE THREAD

**Issue by Abdelrhman-AK** [ModernFlyouts-Community/ModernFlyouts#400]
The Application was unable to start correctly (0xc0000005), inspite of having dotNet Framework 4.8 and C++ 2019 Redistributables.

**OS Version:**
 - Windows 10 Version: 20H2 (Build 19042.746)

**ModernFlyouts Version:**
 - Version: 0.9.0.0

**Comment by Cyberdroid1** [comment]
Can you please share any error window you receive?

Do you use any third party antivirus?

**Comment by davinhanif** [comment]
@Cyberdroid1 I do have the same issue. I have to disable Avast Antivirus each time I login to Windows in order to launch Modern Flyouts manually. Unfortunatelly, reinstalling from Microsoft Store doesn't solve the problem.

![image](https://user-images.githubusercontent.com/39960696/105987219-9093c700-60d0-11eb-8d2c-69711b283286.png)


> Can you please share any error window you receive?
> 
> Do you use any third party antivirus?

**Comment by Cyberdroid1** [comment]
Knew it that this would be issue. To fix this, open your antivirus app and add the folder C:/Program Files/WindowsApps to exception/whitelist.
It should fix the issue.

**Comment by Cyberdroid1** [comment]
We had recently found this issue, about 3 days back, in issue #384. Please have a look at that issue.
