### ISSUE TITLE
Bug: Timestamp/Progress only updates every 3-4 seconds

### ISSUE THREAD

**Issue by luximus-hunter** [ModernFlyouts-Community/ModernFlyouts#427]
**Describe the bug:**
When listening to Spotify, the media player flyout only updates the timestamp/progress every 3-4 seconds.

**To Reproduce:**

**Screenshots:**
n/a

**OS Version:**
Windows 10 Pro Insider Preview Build 21301.rs_prerelease.210123-1645

**ModernFlyouts Version:**
V 0.9.0.0

**Additional context:**
n/a

**Comment by ADeltaX** [comment]
Unfortunately it's not a bug and we can't do nothing (except for music/video apps to do a tiny tweak).
Spotify updates the media timeline every 5 seconds and that's by design. And so many other apps does.

Microsoft recommends to update the media playback timeline approximately every 5 seconds, which is, IMHO, ridiculous. And this is the default behavior.

![image](https://user-images.githubusercontent.com/11020093/107126086-13c1d380-68ae-11eb-89f8-e1dce3cc64fe.png)
Source: https://docs.microsoft.com/en-us/windows/uwp/audio-video-camera/system-media-transport-controls#update-the-system-media-transport-controls-timeline-properties

**Comment by Cyberdroid1** [comment]
It is very ridiculous behaviour. It is MS behaviour.

**Comment by luximus-hunter** [comment]
> Unfortunately it's not a bug and we can't do nothing (except for music/video apps to do a tiny tweak).
> Spotify updates the media timeline every 5 seconds and that's by design. And so many other apps does.
> 
> Microsoft recommends to update the media playback timeline approximately every 5 seconds, which is, IMHO, ridiculous. And this is the default behavior.
> 
> ![image](https://user-images.githubusercontent.com/11020093/107126086-13c1d380-68ae-11eb-89f8-e1dce3cc64fe.png)
> Source: https://docs.microsoft.com/en-us/windows/uwp/audio-video-camera/system-media-transport-controls#update-the-system-media-transport-controls-timeline-properties
@ADeltaX 

Ah, I see. Is there maybe an option to make this a setting so people can overwrite it manually or is that out of the question?

Also, thanks for your quick response 🙂

**Comment by ShankarBUS** [comment]
Arghhhhh! Spotify is retarded! Go and ask them!
