### ISSUE TITLE
Bug: Audio Flyout doesn't work after reboot of the computer

### ISSUE THREAD

**Issue by BestRazer** [ModernFlyouts-Community/ModernFlyouts#433]
After I shutdown the computer and start it up again, the Audio Flyout isn't showing. There's just the normal volume flyout. To fix, I either have to restart the program or disable and enable the Audio Flyout.

**To Reproduce:**

1. Listen to something on Spotify, YouTube, Netflix e.g. so that the Audio Flyout is showing.
2. Reboot the computer
3. Test the Audio Flyout Again.
**Screenshots:**

**OS Version:**
 - Windows 10 Pro Version: 20H2 

**ModernFlyouts Version:**
 - Version: 0.8.5.0 

**Additional context:**

**Comment by Samuel12321** [comment]
@BestRazer  Please update to the latest version (0.9.0) and see if the problem is resolved.

**Comment by BestRazer** [comment]
Doesn't work anyway.

**Comment by Samuel12321** [comment]
@BestRazer does this occur with any of the other flyouts or just the volume flyout?
-Does this occur on normal startup or just on reboot?
-Also just clarifying, does the ModernFlyouts app start normally?

**Comment by fillwithjoy1** [comment]
From #437

**Comment by BestRazer** [comment]
Yes, Modern Flyouts startet normally. What @fillwithjoy1 posted just makes the ModernFlyouts Windows Start Up but the audioflyout only works if I turn it off and back on again.

**Comment by fillwithjoy1** [comment]
@BestRazer That is interesting, maybe posting specs of your computer could help

**Comment by BestRazer** [comment]
Okay, here are my computers specs:
CPU: AMD Ryzen 5 2600
GPU: NVIDIA GeForce GTX 1660 SUPER
RAM: 16 GB DDR4
Windows 10 Pro 64 Bit

**Comment by fillwithjoy1** [comment]
Does it report a syntax error or such at the slider? Sent from Mail for Windows 10 From: BestRazerSent: Tuesday, 9 March 2021 12:41 AMTo: ModernFlyouts-Community/ModernFlyoutsCc: Joy; MentionSubject: Re: [ModernFlyouts-Community/ModernFlyouts] Bug: Audio Flyout doesn't work after reboot of the computer (#433) Yes, Modern Flyouts started normally. What @fillwithjoy1 posted just makes the ModernFlyouts Windows Start Up but the audioflyout only works if I turn it off and back on again.—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by Samuel12321** [comment]
does this still occur on 0.9.3?

**Comment by fillwithjoy1** [comment]
For me it occurs after a while and sometimes it doesn't show whatsoever
after rebooting and I need to outright open the app

**Comment by BestRazer** [comment]
> does this still occur on 0.9.3?

Nope, it works fine now. Thank you!
