### ISSUE TITLE
Feature Request: Audio Flyout additional setting for disabling music progress bar for unsupported apps

### ISSUE THREAD

**Issue by unbekannt3DE** [ModernFlyouts-Community/ModernFlyouts#479]
**Is your feature request related to a problem? Please describe:**
I currently use YT Music as my main music streaming platform and with it a Electron wrapper called YTMDesktop ([ytmdesktop.app](https://ytmdesktop.app)) which has an option to enable Windows 10 media service compatibility but unlike Spotify it unfortunately doesn't expose the track length and current position to it and ModernFlyouts shows an empty progress bar:

![image](https://user-images.githubusercontent.com/10979501/109423440-b5d16900-79df-11eb-9f21-4da1b9539803.png)

I think Deezer currently has the same problem as described in this discussion: #478 

**Describe the solution you'd like:**
The in my case unusable progress bar currently makes the window bigger than it needs to be so it would be a nice to have option in audio settings to disable the bar completely or just for specific .EXEs.

**Describe alternatives you've considered:**
I will create an issue over at the YTMDesktop repo for exposing the additional details to the WMS API but think an option for disabling the progress bar is a good option anyway.

**Comment by Cyberdroid1** [comment]
Regarding the app you request, it was discussed in #388. 

The fact is, the apps have to support GSMTC controls so that ModernFlyouts is able to take advantage of that and support additional features like timeline, shuffle, repeat, etc. 

Apparently, some apps like Deezer, YTM Desktop do not properly support this and hence timeline bar and buttons appear greyed out. This is something that ModernFlyouts cannot fix :/

You may want to open a feature request towards the app dev to request to implement GSMTC support in their apps.

Regarding hiding the timeline bar, we have an issue #392 for the same.

I hope I have answered your queries :)

I will be closing this issue as a duplicate now. If you still have any doubts. you can reopen this issue :)
