### ISSUE TITLE
Support for DPI Awareness

### ISSUE THREAD

**Issue by Samuel12321** [ModernFlyouts-Community/ModernFlyouts#69]
#68

**Comment by ShankarBUS** [comment]
We already have that enabled app manifest, I thought that should work fine. (Not `PerMonitorV2` but `PerMonitor`)

https://github.com/ShankarBUS/ModernFlyouts/blob/bba5b11f4832f8b53b780912362952bf7923fc88/ModernFlyouts/app.manifest#L53

Even if we do anything regarding this in the `app.manifest`, it would be removed in v0.7. Since ModernFlyouts will become a *.dll instead of an *.exe

**Comment by Samuel12321** [comment]
not sure what the problem is, but Microsoft app certification didn't pick it up?

**Comment by ShankarBUS** [comment]
I guess we should use the **`SetProcessDpiAwarenessContext`** instead of the `app.manifest`

**Comment by ShankarBUS** [comment]
Forgot something, Nice!

**Comment by Samuel12321** [comment]
![Screenshot 2020-11-21 104741](https://user-images.githubusercontent.com/35312698/99853007-05391980-2be7-11eb-8fce-a9ba9c6d3c55.png)

**Comment by Cyberdroid1** [comment]
Is this still a problem or fixed?

**Comment by Samuel12321** [comment]
still a problem, @ShankarBUS Any ideas of the cause?

**Comment by ShankarBUS** [comment]
I'll do that ASAP.

Just hit this dpi unawareness issue while working on the positioning logic.

Our app doesn't recognize dpi changes.

I'll need some time.

**Comment by ShankarBUS** [comment]
This could be ignored. RuntimeBroker contains necessary configs enabled for HiDpi support.

**Comment by Cyberdroid1** [comment]
So, counts as fixed? or ignored?
