### ISSUE TITLE
Feature Request: Add the ability to change whether the Media controls appears below or above the Volume controls and and the ability to control the expand direction

### ISSUE THREAD

**Issue by Samuel12321** [ModernFlyouts-Community/ModernFlyouts#71]
@Samuel12321:

In 0.5 we added the ability to change where on the screen the flyout appeared, however if the user moves the flyout to the bottom of the screen, the media flyout can go off the screen.

@jean3x7:

I want to dock the flyout to the bottom without the content being hidden

Current behaviour:
![image](https://user-images.githubusercontent.com/32421544/95529334-0274c300-09b1-11eb-8b7a-84f3e6e966cd.png)
![image](https://user-images.githubusercontent.com/32421544/95529345-0d2f5800-09b1-11eb-9fa4-43aa9b23b81d.png)

Proposed behaviour:
![image](https://user-images.githubusercontent.com/32421544/95529362-18828380-09b1-11eb-8c56-0437e1cd53a2.png)
![image](https://user-images.githubusercontent.com/32421544/95529372-1d473780-09b1-11eb-8fa0-e11f898e0544.png)

**Comment by ShankarBUS** [comment]
This would be hard. Moving the media transport controls to the top won't be hard but the resizing & positioning would be hard.

Because "Auto height" changes only the dimension and not position. So we have to manually anchor the flyout to bottom (i.e move the flyout up/down as the height changes to make it look like anchored to the bottom)

This could be a priority for v0.9?
- We have to refactor all the xaml and C# code and implement MVVM in v0.9.

- Make the flyout support summoning from the tray icon (thus we would to support different direction for different taskbar orientations). While doing this we can do what you suggested.

**Comment by ShankarBUS** [comment]
And FYI, we have the ability to move the flyout since v0.1. But there were no support to save it's location & restore it after a reboot. We added support for saving it in v0.5

**Comment by Samuel12321** [comment]
just requested on store feedback

**Comment by ShankarBUS** [comment]
How ya like dis?

@jean3x7

https://user-images.githubusercontent.com/63704247/104181878-88335f00-5435-11eb-9a4c-84058fa1fc66.mp4

**Comment by Cyberdroid1** [comment]
You did not preview properly :/

**Comment by jean3x7** [comment]
> How ya like dis?
> 
> @jean3x7
> 
>  2021-01-11.17-48-52.mp4

Yes, Exactly! 
Dock to the bottom without hide content of panels (media, volume, caps lock, etc)!
