### ISSUE TITLE
Feature Request:

### ISSUE THREAD

**Issue by Prifixy** [ModernFlyouts-Community/ModernFlyouts#821]
**I'd love to have Discord notifications pop up in Modern Flyouts.**
Because they are way more customizable using Modern Flyouts.

**EXE related question**
Will you guys ever release any EXE files, not requiring the Windows Store/support for older versions/custom ISO's?

**Please note that:**
I have not really looked into any documentation, and I am not aware if its already a thing, but me and friends use this program, and we all have this issue.

**Comment by Samuel12321** [comment]
Right now we don't plan on releasing an .exe installer as it simplifies our workload significantly just having msix.

ModernFlyouts doesn't have to be installed via the ms store, you can also use winget, the msix on github, chocolatey and soon .appinstaller.

Not sure what you mean by custom iso's, but our min windows version requirement is due to limitations of msix and NSMP.
Older versions of ModernFlyouts- prior to  0.4 used .exe and supported down to Windows 8. They can be found on the github downloads section, just remember they may be missing features and contain bugs.

What issue specifically are you having?

What discord notifications, do you mean toast notifications?

**Comment by Prifixy** [comment]
Hi,

Thanks for your reply!

I understand. I just realized that you can unpack the msixbundles and then
unpacking msix. You could then see the exe. Will that work? I currently
can't test because I'm not running Windows 10/11.

I ment ISO's created using debloating tools like NTLite. They remove a lot
of crap such as the windows store and edge. They also remove support for
.appt and .msix installers, that's why I asked.

I ment the notifications that you get from servers and dms when your status
is set to online. They are coming thought as normal windows notifications
instead of modernflyouts notifications. I am almost certain that you guys
did not inplement this kind of thing, and that's why I added this as a
suggestion.

Thanks,
Prifixy

**Comment by Samuel12321** [comment]
- Unpacking the msix and using the exe won't work. The exe is dependent on other components in the bundle.
- We can't support those iso's if they remove critical components such as msix support and appinstaller.
- you are correct we don't support toast notifications. There is another issue open for this.

**Comment by Prifixy** [comment]
alright, thanks.
