### ISSUE TITLE
Bug: Prompt about lock keys changing status is empty

### ISSUE THREAD

**Issue by FadeMind** [ModernFlyouts-Community/ModernFlyouts#851]
**Describe the bug:**

**To Reproduce:**
1. Install cert and dot NET 6.x
2. Install v0.10.0-beta.1 from a file.
3. Launch app.
4. Press INSERT or NUM LOCK or CAPS LOCK.
5. Prompt will be empty.

**Screenshots:**
![20211020-1634730907](https://user-images.githubusercontent.com/9846948/138095264-a3604952-86e5-43b2-a7d8-27ebb9ce22da.png)

**OS Version:**
 - Windows Version: 11 21H2 22000.258

**ModernFlyouts Version:**
 - Version: v0.10.0-beta.1

**Additional context:**
none

**Comment by manstheram** [comment]
I get that it's been a while (a very long while since this issue was opened" but I've fixed this bug and am fixing other bugs so.. https://github.com/manstheram/ModernFlyouts

**Comment by Samuel12321** [comment]
> I get that it's been a while (a very long while since this issue was opened) but I've fixed this bug and am fixing other bugs so.. https://github.com/manstheram/ModernFlyouts

Hi @manstheram ,
It has been a while since any active development has occurred.

We threw all our development effort into our big 0.11 release which got severely delayed. We had intended to rebuild the program based on winui3 and the Windows app sdk, and increase modularity so we could quickly add new flyouts for brightness, as well as tray flyouts for individual app volume control, battery and others.

Unfortunately we ran into blocking issures with the Windows app sdk, and fixes which were promised by Microsoft have only just started to be provided. Unfortunately while waiting, the few developers we had including me have now got less spare time to work on the project. And with Windows 11's new flyouts we have had less developer interest.

The past few months I have been weighing up whether to put up a note that ModernFlyouts was no longer being actively developed, but have always wanted to restart development and keep the project going.

With that being said if you are able to submitt a pr for the fixes you have been working on, I will put together another release.

Thanks,
Sam

**Comment by manstheram** [comment]
Hi @Samuel12321, I'll submit a pr. I've fixed the issue with the Windows 11 flyouts and the Lock buttons.

**Comment by manstheram** [comment]
@Samuel12321 
Just submitted one.

**Comment by Samuel12321** [comment]
Fixed in 0.10.beta3
will be in 0.10 stable
