### ISSUE TITLE
Feature Request: Advanced placement options for different monitors

### ISSUE THREAD

**Issue by hausguests** [ModernFlyouts-Community/ModernFlyouts#861]
**Is your feature request related to a problem? Please describe:**
I use two different monitors (not at the same time), one is 4k and one 1080p, and I switch between them frequently, which means I can't use manual placement settings because it puts the flyout in different places on different resolution monitors. 

**Describe the solution you'd like:**
Some sort of relative location scaling would be nice, maybe if you set it to a certain value on a 1080p monitor it scales your X and Y values up by 4 for a 4k monitor? (and vice versa).
A percentage based padding system could also work, maybe you want it 10% over and 15% down, and it just calculates a pixel value per monitor. 
It would be ideal if X and Y locations in manual placement mode could be set on a per-resolution basis, but this may be difficult to implement so I have no idea.

**Describe alternatives you've considered:**
I'm able to just use auto placement instead, but this isn't ideal since I'm used to having some padding between my flyouts and the edges of my screen.

**Comment by LazieKat** [comment]
I also have 1080 and 4k screens and I'd love that I like my flyout on the top right but auto-placement covers windows' maximize, minimize, and close buttons so I move it 200px lower. I can't set that currently because setting X to 3250 and unplugging from the 4k monitor will place the flyout off-screen on my laptop's 1080 screen.

In addition to your percentage suggestion, I also suggest adding placement pixel-wise with different origins. Right now, the X and Y values place the top left corner of the flyout from the top left corner of the screen, I would love to have the ability to set them to place the top right corner of the flyout relative to the top right corner of the screen (as that works best in my case).

My suggested solution is to use negative values to wrap around the screen (like python array indexing), something like this:

- Negative X: offset from right edge
- Positive X: offset from left edge
- Negative Y: offset from bottom edge
- Positive Y: offset from top edge

This also makes more sense as negative values at the moment just place the flyout off-screen which isn't helpful.

**Comment by jean3x7** [comment]
Please, option to show flyout on active monitor for who have two or more monitors...

**Comment by Samuel12321** [comment]
we are working on this for 0.11

**Comment by Samuel12321** [comment]
Closing in favor of #736
